#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	# active_color=0xc0e2e2e3
    active_color=0xffbb9af7 # Magenta
    # active_color=0xfff7768e # Red
	# inactive_color=0xc02c2e34
    inactive_color=0xc0e2e2e3
	background_color=0x302c2e34
)

borders "${options[@]}"
