#!/bin/bash

light_theme=0xff829181 # Green
dark_theme=0xffbb9af7 # Magenta
echo $CONFIG_THEME

if $CONFIG_THEME == "LIGHT"; then
    theme=$light_theme
else
    theme=$dark_theme
fi

options=(
	style=round # square or round
	width=6.0
	hidpi=on
    # active_color=$theme
	# active_color=0xffe1e3e4 # White
    # active_color=0xffbb9af7 # Magenta
    # active_color=0xff9169c1 # Purple
    # active_color=0xfff7768e # Red
    # active_color=0xff58b99d # Green
    active_color=0xff7aa2f7 # Blue
    # active_color=0xff24283b # Black
    # active_color=0xff7f8490 # Gray
    # active_color=0xffff9e64 # Orange
	# inactive_color=0xc02c2e34
    inactive_color=0xc0e2e2e3
	# background_color=0x302c2e34
)

borders "${options[@]}"
