#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=off
	# active_color=0xc0e2e2e3
    active_color=0xfff7768e
	# inactive_color=0xc02c2e34
    inactive_color=0xc0e2e2e3
	background_color=0x302c2e34
)

borders "${options[@]}"
