#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_shadow off \
	window_animation_duration 0.5 \
    window_animation_easing ease_out_quint \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.5 \
	window_opacity on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 8 \
	bottom_padding 12 \
	left_padding 12 \
	right_padding 12\
	window_gap 8 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:40:0

# Disable specific apps from tiling
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# move some apps automatically to specific spaces
yabai -m rule --add app="^Ghostty$" space=^1
# yabai -m rule --add app="^Slack$" space=4
# yabai -m rule --add app="^Microsoft Outlook$" space=4

# Hack for native tabs in Ghostty
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'
