format = """
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260)\
\n$character"""

command_timeout = 1000

[directory]
style = "fg:#090c0c bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = "󰊤  "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($ahead_behind$stashed$modified$staged)](fg:#769ff0 bg:#394260)]($style)'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = ' ⇣${count} '
stashed = " 󱧕 ${count} "
modified = "  ${count} " 
staged = " 󰜄 ${count} "

[git_metrics]
format = '[ +$added ]($added_style)[-$deleted]($deleted_style)'
added_style = "fg:#769ff0 bg:#394260"
deleted_style = "fg:#769ff0 bg:#394260"
disabled = false

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"
